### ISSUE TITLE
Friendly Captcha support

### ISSUE THREAD

**Issue by marcphilipp** [bramley/phplist-plugin-hcaptcha#1]
Based on this plugin, I've created a plugin to support [Friendly Captchas](https://friendlycaptcha.com/) at https://github.com/marcphilipp/phplist-plugin-friendly-captcha

However, I'm not going to closely follow the development of phpList

@bramley Would you be interested in maintaining that given the number of plugins you already support?

**Comment by bramley** [comment]
I will take a look at what you have done.

**Comment by bramley** [comment]
Your work looks good. After registering with their service I used the plugin to subscribe successfully. By fiddling around I made the invalid solution and duplicate solution errors occur.

I'm happy to maintain the plugin. How do you want to do that, make me a maintainer?

**Comment by marcphilipp** [comment]
I've initiated the repository to be transferred to your username. You should have received an email to accept it.

**Comment by bramley** [comment]
I have been given ownership of the repository and will add a documentation page shortly.
Thanks for making these changes.
